"""add coordinate

Revision ID: 8a8f795c7a83
Revises: e539e5a69478
Create Date: 2023-03-21 11:39:03.110808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a8f795c7a83'
down_revision = 'e539e5a69478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Construction', sa.Column('reprsnt_coord_lat', sa.String(length=20), nullable=True))
    op.add_column('Construction', sa.Column('reprsnt_coord_lng', sa.String(length=20), nullable=True))
    op.alter_column('Construction', 'gis_data',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Construction', 'gis_data',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('Construction', 'reprsnt_coord_lng')
    op.drop_column('Construction', 'reprsnt_coord_lat')
    # ### end Alembic commands ###
