"""db_scheme

Revision ID: e539e5a69478
Revises: 379618dd5ca6
Create Date: 2023-03-08 02:31:16.021869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e539e5a69478'
down_revision = '379618dd5ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Construction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gis_data', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.String(length=100), nullable=True),
    sa.Column('pyeong_cost', sa.Integer(), nullable=True),
    sa.Column('donation_land_ratio', sa.Float(), nullable=True),
    sa.Column('BSNS_PK', sa.String(length=50), nullable=False),
    sa.Column('GU_NM', sa.String(length=30), nullable=False),
    sa.Column('BJDON_NM', sa.String(length=30), nullable=False),
    sa.Column('BTYP_NM', sa.String(length=30), nullable=False),
    sa.Column('STEP_SE_NM', sa.String(length=30), nullable=False),
    sa.Column('CAFE_NM', sa.String(length=100), nullable=False),
    sa.Column('REPRSNT_JIBUN', sa.String(length=30), nullable=False),
    sa.Column('PROGRS_STTUS', sa.String(length=30), nullable=False),
    sa.Column('CAFE_STTUS', sa.String(length=30), nullable=False),
    sa.Column('ZONE_NM', sa.String(length=100), nullable=True),
    sa.Column('ZONE_ADRES', sa.String(length=100), nullable=True),
    sa.Column('ZONE_AR', sa.Float(), nullable=True),
    sa.Column('TOTAR', sa.Float(), nullable=True),
    sa.Column('CTY_PLAN_SPFC_NM', sa.String(length=200), nullable=True),
    sa.Column('CTY_PLAN_SPCFC_NM', sa.String(length=200), nullable=True),
    sa.Column('LAD_BLDLND_AR', sa.Float(), nullable=True),
    sa.Column('LAD_PBSPCE_AR', sa.Float(), nullable=True),
    sa.Column('LAD_ROAD_AR', sa.Float(), nullable=True),
    sa.Column('LAD_PARK_AR', sa.Float(), nullable=True),
    sa.Column('LAD_GREENS_AR', sa.Float(), nullable=True),
    sa.Column('LAD_SCHUL_AR', sa.Float(), nullable=True),
    sa.Column('LAD_ETC_AR', sa.Float(), nullable=True),
    sa.Column('BILDNG_PRPOS_NM', sa.String(length=100), nullable=True),
    sa.Column('BILDNG_BDTLDR', sa.Float(), nullable=True),
    sa.Column('BILDNG_FLRSPCER', sa.Float(), nullable=True),
    sa.Column('BILDNG_HG', sa.Float(), nullable=True),
    sa.Column('BILDNG_GROUND_FLOOR_CO', sa.Integer(), nullable=True),
    sa.Column('BILDNG_UNDGRND_FLOOR_CO', sa.Integer(), nullable=True),
    sa.Column('SUM_BILDNG_CO', sa.Integer(), nullable=True),
    sa.Column('BILDNG_60_CO', sa.Integer(), nullable=True),
    sa.Column('BILDNG_60_85_CO', sa.Integer(), nullable=True),
    sa.Column('BILDNG_85_CO', sa.Integer(), nullable=True),
    sa.Column('BILDNG_RM', sa.String(length=200), nullable=True),
    sa.Column('LOCIMG01', sa.String(length=200), nullable=True),
    sa.Column('LOCIMG02', sa.String(length=200), nullable=True),
    sa.Column('LOCIMG03', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('News',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('thumnl_url', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('keywords', sa.String(length=1000), nullable=True),
    sa.Column('ks_graph', sa.String(length=50), nullable=True),
    sa.Column('pubdate', sa.String(length=50), nullable=True),
    sa.Column('media', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['Construction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('construction_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=True),
    sa.Column('avg_land_area', sa.Float(), nullable=True),
    sa.Column('freq_purpose_area_1', sa.JSON(), nullable=True),
    sa.Column('freq_purpose_area_2', sa.JSON(), nullable=True),
    sa.Column('freq_land_use_situation', sa.JSON(), nullable=True),
    sa.Column('freq_topography_height', sa.JSON(), nullable=True),
    sa.Column('freq_topography_form', sa.JSON(), nullable=True),
    sa.Column('freq_road_side_type', sa.JSON(), nullable=True),
    sa.Column('cnt_lot', sa.Integer(), nullable=True),
    sa.Column('avg_price_by_year', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['Construction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('pnu', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=1024), nullable=True),
    sa.Column('land_use_type', sa.String(length=10), nullable=True),
    sa.Column('land_area', sa.Integer(), nullable=True),
    sa.Column('purpose_area_1', sa.String(length=30), nullable=True),
    sa.Column('purpose_area_2', sa.String(length=30), nullable=True),
    sa.Column('land_use_situation', sa.String(length=10), nullable=True),
    sa.Column('topography_height', sa.String(length=10), nullable=True),
    sa.Column('topography_form', sa.String(length=10), nullable=True),
    sa.Column('road_side_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['Construction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprice_simulation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('pre_simul_date', sa.Integer(), nullable=False),
    sa.Column('pre_predicted_prc', sa.Integer(), nullable=False),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['Construction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('pyeong_type', sa.Integer(), nullable=False),
    sa.Column('request_land', sa.Float(), nullable=False),
    sa.Column('num_copartner_building', sa.Integer(), nullable=False),
    sa.Column('num_general_building', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['Construction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postprice_simulation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('post_simul_date', sa.Integer(), nullable=False),
    sa.Column('post_predicted_prc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sale_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postprice_simulation')
    op.drop_table('lot_price')
    op.drop_table('sale_information')
    op.drop_table('preprice_simulation')
    op.drop_table('lot')
    op.drop_table('construction_stat')
    op.drop_table('News')
    op.drop_table('Construction')
    # ### end Alembic commands ###
